# Generated by Django 5.1.5 on 2025-01-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ticket_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='decision',
            field=models.TextField(null=True),
        ),
    ]
