# Generated by Django 5.1.5 on 2025-01-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
