from django.urls import path
from core.views import (index,
                        about,
                        new_ticket,
                        add_ticket,
                        delete_ticket,
                        edit_ticket,
                        close_ticket,
                        my_ticket,
                        ticket_to_process,
                        process_ticket,
                        complete_ticket,
                        check_ticket_status,
                        back_office_rep,
                        report_page,
                        export_to_excel,
                        check_comment_ticket_status,
                        comment_ticket,
                        ticket_details)
urlpatterns = [
    path('', index, name='index'),    
    path('about/', about, name='about'),
    path('new-ticket/', new_ticket, name='new_ticket'),
    path('add-ticket/', add_ticket, name='add_ticket'),
    path('delete-ticket/<int:ticket_id>/', delete_ticket, name='delete-ticket'),
    path('edit-ticket/<int:ticket_id>/', edit_ticket, name='edit-ticket'),
    path('close-ticket/<int:ticket_id>/', close_ticket, name='close-ticket'),
    path('my-ticket/', my_ticket, name='my_ticket'),
    path('ticket-to-process/', ticket_to_process, name='ticket-to-process'),
    path('process-ticket/<int:ticket_id>/', process_ticket, name='process-ticket'),
    path('complete-ticket/<int:ticket_id>/', complete_ticket, name='complete-ticket'),
    path('complete-ticket/<int:ticket_id>/check-status/', check_ticket_status, name='check_ticket_status'),
    path('back-office-rep/', back_office_rep, name='back-office-rep'),
    path('reports/',  report_page, name='report_page'),
    path('export-to-excel/', export_to_excel, name='export_to_excel'),
    path('comment-ticket/<int:ticket_id>/', comment_ticket, name='comment-ticket'),
    path('comment-ticket/<int:ticket_id>/check-status/', check_comment_ticket_status, name='check_comment_ticket_status'),
    path('ticket-details/<int:ticket_id>/', ticket_details, name='ticket-details'),
]
